apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
    spec:
      containers:
        - name: admin-service
          image: kacytunde/admin-service:1.8
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "100"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://xykine-postgres/xykinedb_payroll
            - name: SPRING_DATASOURCE_USERNAME
              value: xykine
            - name: SPRING_DATASOURCE_PASSWORD
              value: xykine123
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb+srv://xykinehrs:I4jY8L79v5m1EK20@xykinehrsdb-05d564e8.mongo.ondigitalocean.com/xykinehrsdb?tls=true&authSource=admin&replicaSet=xykinehrsdb
            - name: SPRING_DATA_MONGODB_DATABASE
              value: xykinehrsdb
            #            - name: SPRING_PROFILES_ACTIVE
#              value: dev
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://xykine.com/realms/AcedPayroll
            - name: SF_API_KEY
              value: hp7HBn5UmlDN2rAbFruxcSNnxhy0AYNM
#          resources:
#            requests:
#              memory: "1Gi"  # Request 1GB of memory
#            limits:
#              memory: "2Gi"  # Limit memory usage to 2GB
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 9001
#            initialDelaySeconds: 10
#            periodSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 9001
#            initialDelaySeconds: 5
#            periodSeconds: 15
