apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-ui
  labels:
    app: payroll-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll-ui
  template:
    metadata:
      labels:
        app: payroll-ui
    spec:
      containers:
        - name: payroll-ui
          image: kacytunde/payroll-ui:2.5
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---

apiVersion: v1
kind: Service
metadata:
  name: payroll-ui
  labels:
    app: payroll-ui
spec:
  type: ClusterIP
  selector:
    app: payroll-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000