apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-ui
  template:
    metadata:
      labels:
        app: scheduler-ui
    spec:
      containers:
        - name: scheduler-ui
          image: kacytunde/scheduler-ui:latest
          ports:
            - containerPort: 3001

