apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: kacytunde/edge-service:1.0
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9000
          env:
            - name: SPA_URL
              value: http://payroll-ui
            - name: SCHEDULER_URL
              value: http://scheduler-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: ADMIN_SERVICE_URL
              value: http://admin-service
            - name: PAY_COMPUTATION_SERVICE_URL
              value: http://paycomputation-service
#            - name: SPRING_REDIS_HOST
#              value: xykine-redis
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb+srv://xykinehrs:I4jY8L79v5m1EK20@xykinehrsdb-05d564e8.mongo.ondigitalocean.com/xykinehrsdb?tls=true&authSource=admin&replicaSet=xykinehrsdb
            - name: SPRING_DATA_MONGODB_DATABASE
              value: xykinehrsdb
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: http://xykine.com/realms/XykinePayroll
#              value: http://localhost/realms/Payroll
