apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  selector:
    app: edge-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
#apiVersion: v1
#kind: Service
#metadata:
#  name: edge-service
#  annotations:
#    kubernetes.digitalocean.com/load-balancer-id: "ae6c8bfd677754e9caaeb8922a426143"
#    service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"
#    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
#  labels:
#    app: edge-service
#spec:
#  type: LoadBalancer
#  externalIPs:
#    - 134.122.107.57
#  selector:
#    app: edge-service
#  ports:
#    - name: http
#      protocol: TCP
#      port: 80
#      targetPort: 9000
